# File runs in GitHub Actions if it is in .github/workflows directory
# Mains structure = Workflow, Jobs, Steps
name: 01 - Building Blocks    # Name of workflow
on:
  #- push                      # Run on push
  - workflow_dispatch         # Run on demand
jobs:                         # Jobs run in parallel by default
  echo-hello:
    runs-on: ubuntu-latest
    steps:                    # Steps run sequentially
      - name: Say hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Passing step
        run: |
          echo "I am"
          echo "a multi-line"
          echo "script."
          exit 0
        # A Non Zero code will fail the step
      - name: Say goodbye
        run: echo "Goodbye!"

  

  