name: 02 - Workflow Events 
on: 
    #push:
    #pull_request:  # feature branch
    workflow_dispatch:
    schedule:  # Can't seem to get cron job working
        - cron: '*/5 * * * *'   # Every 5 minute is lowest it can run https://crontab.cronhub.io/
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{ github.event_name }}"
            
