name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        # checkout code from repository
        # install dependencies
        # run automated tests
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Depedencies
              run: npm ci
              working-directory: 04-using-actions/udemygithubcourse