name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        # checkout code from repository
        # install dependencies
        # run automated tests
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls