name: 07-expressions.yaml
on:
  push:
  workflow_distpatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.action_ref}}"
          echo "Commit SHA: ${{github.sha}}"  
      - name: [debug] Print when triggered from main
        if: ${{inputs.debug}} == true && ${{github.action_ref}} == "main"
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"
        
