# File runs in GitHub Actions if it is in .github/workflows directory
# Main structure = Workflow, Jobs, Steps
name: Print Files Pushed             # Name of workflow
on:
  push:                              # Run on push
    #branches:
      #- KevinGitHubActionsTesting
  workflow_dispatch:                 # Run on demand
jobs:                                # Jobs run in parallel by default
  list-changed-files:
    runs-on: ubuntu-latest
    steps:                          # Steps run sequentially
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed_files
        run: |
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" >> $GITHUB_OUTPUT
      - name: List changed files
        run: |
            echo "Changed files for commit ${{ github.sha }}"
            for file in ${{ steps.changed_files.outputs.changed_files }}; do
                echo $file
            done
